compile:
	clear
	clang++ -g std=c++14 ./*.cpp -o output
	./output
log:
	clear
	clang++ -DDEBUG -g -std=c++14 ./*.cpp -o output
	./output
log3:
	clear
	clang++ -DDEBUG -DLOG_LEVEL=3 -g -std=c++14 ./*cpp -o output
	./output
log1:
	clear
	clang